image: node:10.15.3

clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build
        caches:
          - node
        script:
          - npm install
          - npm build
          
  branches:
    prod:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm build
      - step:
          name: Deploy to Production
          deployment: Production
          script:
            - git push https://heroku:$heroku_api_key@git.heroku.com/$heroku_app_name.git master
       