image: node:10.15.3

clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build
        caches:
          - node
        script:
          - npm install
          - npm build
          
  branches:
    prod:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm build
            - git archive --format=tar.gz main -o app.tar.gz
      - step:
          name: Deploy to Production
          deployment: Production
          caches:
          - node
          script:
            - pipe: atlassian/heroku-deploy:1.2.1
              variables:
                HEROKU_API_KEY: $heroku_api_key
                HEROKU_APP_NAME: $heroku_app_name
                ZIP_FILE: app.tar.gz
       